version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          BUNDLER_VERSION: 2.0.2
      - image: circleci/mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_name_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundler
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundler
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          BUNDLER_VERSION: 2.0.2
      - image: circleci/mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_name_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundler
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundler
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load 
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop